name: dart_openai_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"


resolution: workspace

dependencies:
  path: ^1.8.0
  dart_openai:
    path: ../
  envied: ^1.3.2
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^1.2.0
  lints: ^6.0.0
  test: ^1.24.9
